[project]
name = "tigo-mcp-server"
version = "0.1.0"
description = "Tigo MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.4",
    "tigo-python",
]

[tool.uv.sources]
tigo-python = { path = "../tigo_python" }
